f = open("./test.txt","r",encoding="UTF-8")
# 文件不存在报错
# Traceback (most recent call last):
#   File "F:\Python_learning\python异常、模块与包\01.Python 异常.py", line 1, in <module>
#     f = open("./test.txt","r",encoding="UTF-8")
# FileNotFoundError: [Errno 2] No such file or directory: './test.txt'